name: ci-test

# events
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# jobs
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    # steps
    steps:

    # install go into the runner using existing action
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.23.2
      id: go
    
    # checkout code of repo into the runner using existing action
    - name: Check out code code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: make test